//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductSeriesInfo
    {
        public int ProductSeriesInfoID { get; set; }
        public string Airfoils { get; set; }
        public string Arifoils_Finishes { get; set; }
        public string Hardware_Finishes { get; set; }
        public string Motor { get; set; }
        public string Energy_Efficiency { get; set; }
        public string Controls { get; set; }
        public string Onboard_Sensors { get; set; }
        public string Environment { get; set; }
        public string Accessories { get; set; }
        public string Patented { get; set; }
        public string Manufacturer_Origin { get; set; }
        public int ProductsID { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
    }
}
