//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduct()
        {
            this.tblProductsDetails = new HashSet<tblProductsDetail>();
        }
    
        public int ProductID { get; set; }
        public string Manufacturer { get; set; }
        public string ProductName { get; set; }
        public string Series { get; set; }
        public string Model { get; set; }
        public Nullable<System.DateTime> Model_Year { get; set; }
        public string FeaturedTag { get; set; }
        public string Use_Type { get; set; }
        public string Application { get; set; }
        public string Mounting_Location { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProductsDetail> tblProductsDetails { get; set; }
        public virtual tblSubCategory tblSubCategory { get; set; }
    }
}
