//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductsDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProductsDetail()
        {
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int ProductsDetailsID { get; set; }
        public string AirFlow { get; set; }
        public string SoundAtMaxSpeed { get; set; }
        public Nullable<decimal> FanDiameter { get; set; }
        public string Weights { get; set; }
        public string MaxPower { get; set; }
        public string MinPower { get; set; }
        public string MaxVoltage { get; set; }
        public string MinVoltage { get; set; }
        public string MaxHeight { get; set; }
        public string MinHeight { get; set; }
        public Nullable<int> MaxFanSpeed { get; set; }
        public Nullable<int> MinFanSpeed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
